/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Negocio.EmpleadoNegocio;
import Entidades.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author leona
 */
public class FrmEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEmpleados
     */
    private final EmpleadoNegocio CONTROL;
    private String accion;
    private Empleado empleado;
    private String resp;
    private int Id_empleado;

    public FrmEmpleados() {
        initComponents();
        this.CONTROL = new EmpleadoNegocio();
        this.listar("");
        TabEmpleados.setEnabledAt(1, false);
        TabEmpleados.setEnabledAt(0, true);
        TabEmpleados.setSelectedIndex(0);
        this.accion = "Guardar";
    }

    private void listar(String texto) {
        TblEmpleados.setModel(this.CONTROL.listar(texto));
    }

    private void limpiar() {
        this.TxtNombre.setText("");
        this.TxtDoc.setText("");
        this.TxtTelefono.setText("");
        this.TxtSalario.setText("");

        /* MODIFICACIÓN PARA LOS COMBOBOXES CON setSelectedIndex(-1) */
        if (CbxTurno.getItemCount() > 0) {
            this.CbxTurno.setSelectedIndex(-1);
        } else {
            this.CbxTurno.setSelectedItem(null);
        }

        this.accion = "Guardar";
        this.Id_empleado = 0;
        this.empleado = null;
    }

    private void limpiarCampos() {
        TxtNombre.setText("");
        TxtDoc.setText("");
        TxtTelefono.setText("");
        CbxTurno.setSelectedIndex(0);
    }

    private void cargarTurnos() {
        CbxTurno.removeAllItems();
        CbxTurno.addItem("Mañana");
        CbxTurno.addItem("Tarde");
        CbxTurno.addItem("Noche");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabEmpleados = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtBusqueda = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnInsertar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblEmpleados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtDoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        CbxTurno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        BtnCerrar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento de Empleados");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Busqueda");

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnInsertar.setText("Insertar");
        BtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        TblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnBuscar)
                        .addGap(46, 46, 46)
                        .addComponent(BtnInsertar)
                        .addGap(28, 28, 28)
                        .addComponent(BtnEditar)
                        .addGap(28, 28, 28)
                        .addComponent(BtnEliminar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnInsertar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        TabEmpleados.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DNI");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono");

        CbxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarde", "Noche", "Mañana" }));
        CbxTurno.setSelectedIndex(-1);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Turno");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Salario");

        BtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        BtnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnCerrar)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CbxTurno, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                        .addGap(44, 44, 44)
                        .addComponent(BtnGuardar)))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCerrar)
                    .addComponent(BtnGuardar))
                .addGap(37, 37, 37))
        );

        TabEmpleados.addTab("MANTENIMIENTO", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabEmpleados)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabEmpleados)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        Empleado emp = new Empleado();
        emp.setNombres(TxtNombre.getText());
        emp.setDNI(TxtDoc.getText());
        emp.setTelefono(TxtTelefono.getText());
        emp.setTurno((String) CbxTurno.getSelectedItem());
        emp.setSalario(Double.parseDouble(this.TxtSalario.getText()));

        if (this.accion.equals("Guardar")) {
            resp = this.CONTROL.insertar(emp);
            if (resp.equals("Ok")) {
                JOptionPane.showMessageDialog(null, "Categoria registrado con exito");
                this.limpiar();
                this.listar("");
                TabEmpleados.setEnabledAt(0, true);
                TabEmpleados.setEnabledAt(1, false);
                TabEmpleados.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, resp);
            }
        } else if (this.accion.equals("Editar")) {
            emp.setId_Empleado(this.Id_empleado);
            resp = this.CONTROL.modificar(emp);
            if (resp.equals("Ok")) {
                JOptionPane.showMessageDialog(null, "Categoria modificada con exito");
                this.limpiar();
                this.listar("");
                TabEmpleados.setEnabledAt(0, true);
                TabEmpleados.setEnabledAt(1, false);
                TabEmpleados.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, resp);
            }
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if (TblEmpleados.getSelectedRowCount() == 1) {
            String Id_Empleado = String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 0));
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de eliminar este Producto?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(Id_Empleado);
                String resp = this.CONTROL.eliminar(id);
                if (resp.equals("Ok")) {
                    JOptionPane.showMessageDialog(null, "Empleado eliminado con éxito");
                    this.listar("");
                } else {
                    JOptionPane.showMessageDialog(null, resp);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto a eliminar");
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarActionPerformed
        this.limpiar();
        TabEmpleados.setEnabledAt(0, false);
        TabEmpleados.setEnabledAt(1, true);
        TabEmpleados.setSelectedIndex(1);
        this.accion = "Guardar";
        BtnGuardar.setText("Guardar");
    }//GEN-LAST:event_BtnInsertarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        if (TblEmpleados.getSelectedRowCount() == 1) {
            try {
                this.Id_empleado = Integer.parseInt(String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 0)));
                String Nombres = String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 1));
                String DNI = String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 2));
                String Telefono = String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 3));
                String Turno = String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 4));
                double Salario = Double.parseDouble(String.valueOf(TblEmpleados.getValueAt(TblEmpleados.getSelectedRow(), 5)));

                this.empleado = new Empleado(this.Id_empleado, Nombres, DNI, Telefono, Turno, Salario);

                this.TxtNombre.setText(Nombres);
                this.TxtDoc.setText(DNI);
                this.TxtTelefono.setText(String.valueOf(Telefono));
                this.TxtSalario.setText(String.valueOf(Salario));
                CbxTurno.setSelectedItem(String.valueOf(Turno));
               


                TabEmpleados.setEnabledAt(0, false);
                TabEmpleados.setEnabledAt(1, true);
                TabEmpleados.setSelectedIndex(1);
                this.accion = "Editar";
                BtnGuardar.setText("Editar");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al parsear datos de la tabla: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar datos para edición: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado para editar.");
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        this.listar(this.TxtBusqueda.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.limpiar();
        TabEmpleados.setEnabledAt(0, true);
        TabEmpleados.setEnabledAt(1, false);
        TabEmpleados.setSelectedIndex(0);
    }//GEN-LAST:event_BtnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnInsertar;
    private javax.swing.JComboBox<String> CbxTurno;
    private javax.swing.JTabbedPane TabEmpleados;
    private javax.swing.JTable TblEmpleados;
    private javax.swing.JTextField TxtBusqueda;
    private javax.swing.JTextField TxtDoc;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
