/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidades.Categoria;
import Entidades.Marca;
import Entidades.Producto;
import Negocio.ProductoNegocio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leona
 */
public class FrmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProductos
     */
    private final ProductoNegocio CONTROL;
    private String accion;
    private Producto producto;
    private String resp;
    private int Id_producto;

    public FrmProductos() {
        initComponents();
        this.CONTROL = new ProductoNegocio();
        this.listar("");
        this.cargarCategorias();
        this.cargarMarcas();
        TabProductos.setEnabledAt(1, false);
        TabProductos.setEnabledAt(0, true);
        TabProductos.setSelectedIndex(0);
        this.accion = "Guardar";
    }

    private void listar(String texto) {
        TblProductos.setModel(this.CONTROL.listar(texto));

        if (TblProductos.getColumnModel().getColumnCount() > 1) {
            TblProductos.getColumnModel().getColumn(1).setMinWidth(0);
            TblProductos.getColumnModel().getColumn(1).setMaxWidth(0);
            TblProductos.getColumnModel().getColumn(1).setWidth(0);
        }
        if (TblProductos.getColumnModel().getColumnCount() > 3) {
            TblProductos.getColumnModel().getColumn(3).setMinWidth(0);
            TblProductos.getColumnModel().getColumn(3).setMaxWidth(0);
            TblProductos.getColumnModel().getColumn(3).setWidth(0);
        }
    }

    private void limpiar() {
        this.TxtNombre.setText("");
        this.TxtDescripcion.setText("");
        this.TxtStock.setText("");
        this.TxtPreciou.setText("");

        /* MODIFICACIÓN PARA LOS COMBOBOXES CON setSelectedIndex(-1) */
        if (CbxCategoria.getItemCount() > 0) {
            this.CbxCategoria.setSelectedIndex(-1);
        } else {
            this.CbxCategoria.setSelectedItem(null);
        }

        if (CbxMarca.getItemCount() > 0) {
            this.CbxMarca.setSelectedIndex(-1);
        } else {
            this.CbxMarca.setSelectedItem(null);
        }

        CbxMarca.setSelectedItem(null);

        this.accion = "Guardar";
        this.Id_producto = 0;
        this.producto = null;
    }

    private void cargarCategorias() {
        CbxCategoria.setModel(this.CONTROL.seleccionar());
    }

    private void cargarMarcas() {
        CbxMarca.setModel(this.CONTROL.seleccionarmar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabProductos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LblBusqueda = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnInsertar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        LblCategoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtPreciou = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CbxMarca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TxtStock = new javax.swing.JTextField();
        CbxCategoria = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento de Productos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LblBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        LblBusqueda.setText("Busqueda");

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnInsertar.setText("Insertar");
        BtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        TblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LblBusqueda)
                .addGap(28, 28, 28)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(BtnBuscar)
                .addGap(24, 24, 24)
                .addComponent(BtnInsertar)
                .addGap(29, 29, 29)
                .addComponent(BtnEditar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBusqueda)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnInsertar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        TabProductos.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        LblCategoria.setForeground(new java.awt.Color(0, 0, 0));
        LblCategoria.setText("Categoria");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Precio Venta");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca");

        CbxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxMarcaItemStateChanged(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripción");

        TxtDescripcion.setColumns(20);
        TxtDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxtDescripcion);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Stock");

        CbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxCategoriaItemStateChanged(evt);
            }
        });
        CbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblCategoria)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtPreciou, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CbxCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CbxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, 235, Short.MAX_VALUE)))))
                        .addGap(28, 28, 28)
                        .addComponent(BtnGuardar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCategoria)
                    .addComponent(CbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtPreciou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCerrar)
                    .addComponent(BtnGuardar))
                .addGap(16, 16, 16))
        );

        TabProductos.addTab("MANTENIMIENTO", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabProductos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabProductos, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        this.listar(this.TxtBuscar.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarActionPerformed
        this.limpiar();
        TabProductos.setEnabledAt(0, false);
        TabProductos.setEnabledAt(1, true);
        TabProductos.setSelectedIndex(1);
        this.accion = "Guardar";
        BtnGuardar.setText("Guardar");
    }//GEN-LAST:event_BtnInsertarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        if (TblProductos.getSelectedRowCount() == 1) {
            try {
                this.Id_producto = Integer.parseInt(String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 0)));
                int Id_Categoria = Integer.parseInt(String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 1)));
                String categoriaNombre = String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 2));
                int Id_Marca = Integer.parseInt(String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 3)));
                String marcaNombre = String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 4));
                String Nombre = String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 5));
                String Descripcion = String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 6));
                double Precio_U = Double.parseDouble(String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 7)));
                int Stock = Integer.parseInt(String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 8)));

                this.producto = new Producto(this.Id_producto, Id_Categoria, categoriaNombre, Id_Marca, marcaNombre, Nombre, Descripcion, Precio_U, Stock);

                this.TxtNombre.setText(Nombre);
                this.TxtDescripcion.setText(Descripcion);
                this.TxtStock.setText(String.valueOf(Stock));
                this.TxtPreciou.setText(String.valueOf(Precio_U));

                for (int i = 0; i < CbxCategoria.getItemCount(); i++) {
                    Categoria cat = (Categoria) CbxCategoria.getItemAt(i);
                    if (cat.getId_Categoria() == Id_Categoria) {
                        CbxCategoria.setSelectedItem(cat);
                        break;
                    }
                }

                for (int i = 0; i < CbxMarca.getItemCount(); i++) {
                    Marca mar = (Marca) CbxMarca.getItemAt(i);
                    if (mar.getId_Marca() == Id_Marca) {
                        CbxMarca.setSelectedItem(mar);
                        break;
                    }
                }

                TabProductos.setEnabledAt(0, false);
                TabProductos.setEnabledAt(1, true);
                TabProductos.setSelectedIndex(1);
                this.accion = "Editar";
                BtnGuardar.setText("Editar");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al parsear datos de la tabla: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar datos para edición: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto para editar.");
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if (TblProductos.getSelectedRowCount() == 1) {
            String Id_Producto = String.valueOf(TblProductos.getValueAt(TblProductos.getSelectedRow(), 0));
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de eliminar este Producto?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(Id_Producto);
                String resp = this.CONTROL.eliminar(id);
                if (resp.equals("Ok")) {
                    JOptionPane.showMessageDialog(null, "Producto eliminado con éxito");
                    this.listar("");
                } else {
                    JOptionPane.showMessageDialog(null, resp);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto a eliminar");
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void CbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCategoriaActionPerformed

    }//GEN-LAST:event_CbxCategoriaActionPerformed

    private void CbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxCategoriaItemStateChanged
    }//GEN-LAST:event_CbxCategoriaItemStateChanged

    private void CbxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxMarcaItemStateChanged

    }//GEN-LAST:event_CbxMarcaItemStateChanged

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        producto = new Entidades.Producto();

        Categoria categoriaSeleccionada = (Categoria) this.CbxCategoria.getSelectedItem();
        if (categoriaSeleccionada != null) {
            producto.setId_Categoria(categoriaSeleccionada.getId_Categoria());
            producto.setcategoriaNombre(categoriaSeleccionada.getNombre());
        }

        Marca marcaSeleccionada = (Marca) this.CbxMarca.getSelectedItem();
        if (marcaSeleccionada != null) {
            producto.setId_Marca(marcaSeleccionada.getId_Marca());
            producto.setmarcaNombre(marcaSeleccionada.getNombre());
        }
        producto.setNombre(this.TxtNombre.getText());
        producto.setDescripcion(this.TxtDescripcion.getText());
        producto.setStock(Integer.parseInt(this.TxtStock.getText()));
        producto.setPrecio_U(Double.parseDouble(this.TxtPreciou.getText()));

        if (this.accion.equals("Guardar")) {
            resp = this.CONTROL.insertar(producto);
            if (resp.equals("Ok")) {
                JOptionPane.showMessageDialog(null, "Producto registrado con exito");
                this.limpiar();
                this.listar("");
                TabProductos.setEnabledAt(0, true);
                TabProductos.setEnabledAt(1, false);
                TabProductos.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, resp);
            }
        } else if (this.accion.equals("Editar")) {
            producto.setId_Producto(this.Id_producto);
            resp = this.CONTROL.modificar(producto);
            if (resp.equals("Ok")) {
                JOptionPane.showMessageDialog(null, "Producto modificado con exito");
                this.limpiar();
                this.listar("");
                TabProductos.setEnabledAt(0, true);
                TabProductos.setEnabledAt(1, false);
                TabProductos.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, resp);
            }
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.limpiar();
        this.listar("");
        TabProductos.setEnabledAt(0, true);
        TabProductos.setEnabledAt(1, false);
        TabProductos.setSelectedIndex(0);
    }//GEN-LAST:event_BtnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnInsertar;
    private javax.swing.JComboBox<Categoria> CbxCategoria;
    private javax.swing.JComboBox<Marca> CbxMarca;
    private javax.swing.JLabel LblBusqueda;
    private javax.swing.JLabel LblCategoria;
    private javax.swing.JTabbedPane TabProductos;
    private javax.swing.JTable TblProductos;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextArea TxtDescripcion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPreciou;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
