/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Presentacion;

import static java.awt.GridBagConstraints.BOTH;

/**
 *
 * @author leona
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        desactivarMenus();
        
        FrmLogin acc = new FrmLogin(this);
        Principal.add(acc);

        // calcular el centro el denteo de la pantall
        int x = (Principal.getWidth() - acc.getWidth()) / 2;
        int y = (Principal.getHeight() - acc.getHeight()) / 2;

        acc.setLocation(x, y);
        acc.setVisible(true);
        
    }
    
    //metodo para desactivar lo menus
    public void desactivarMenus() {
        jMenu1.setEnabled(false);
        jMenu2.setEnabled(false);
        Compra.setEnabled(false);
        Cerrar.setEnabled(false);
    }
    
    //metodo paraactivar los menus, se llamado desde el formulario de Acceso
    public void activarMenus() {
        jMenu1.setEnabled(true);
        jMenu2.setEnabled(true);
        Compra.setEnabled(true);
        Cerrar.setEnabled(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteDAO1 = new Datos.ClienteDAO();
        Principal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MniCategoria = new javax.swing.JMenuItem();
        MniArticulos = new javax.swing.JMenuItem();
        MniMarcas = new javax.swing.JMenuItem();
        MniClientes = new javax.swing.JMenuItem();
        MniEmpleado = new javax.swing.JMenuItem();
        MniProveedores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MniVenta = new javax.swing.JMenuItem();
        Compra = new javax.swing.JMenu();
        MniCompra = new javax.swing.JMenuItem();
        Cerrar = new javax.swing.JMenu();
        MniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/mantenimiento.png"))); // NOI18N
        jMenu1.setText("Mantenimientos");

        MniCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/categorias.png"))); // NOI18N
        MniCategoria.setText("Categorias");
        MniCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(MniCategoria);

        MniArticulos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/product.png"))); // NOI18N
        MniArticulos.setText("Articulos");
        MniArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniArticulosActionPerformed(evt);
            }
        });
        jMenu1.add(MniArticulos);

        MniMarcas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/marca.png"))); // NOI18N
        MniMarcas.setText("Marcas");
        MniMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniMarcasActionPerformed(evt);
            }
        });
        jMenu1.add(MniMarcas);

        MniClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/nueva-cuenta.png"))); // NOI18N
        MniClientes.setText("Clientes");
        MniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniClientesActionPerformed(evt);
            }
        });
        jMenu1.add(MniClientes);

        MniEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/alquiler.png"))); // NOI18N
        MniEmpleado.setText("Empleados");
        MniEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(MniEmpleado);

        MniProveedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/cadena-de-suministro.png"))); // NOI18N
        MniProveedores.setText("Proveedores");
        MniProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniProveedoresActionPerformed(evt);
            }
        });
        jMenu1.add(MniProveedores);

        menuBar.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/venta.png"))); // NOI18N
        jMenu2.setText("Ventas");

        MniVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/comprobado.png"))); // NOI18N
        MniVenta.setText("Ventas");
        MniVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniVentaActionPerformed(evt);
            }
        });
        jMenu2.add(MniVenta);

        menuBar.add(jMenu2);

        Compra.setBackground(new java.awt.Color(255, 255, 255));
        Compra.setForeground(new java.awt.Color(0, 0, 0));
        Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/compras.png"))); // NOI18N
        Compra.setText("Compras");

        MniCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/bolsa-de-la-compra.png"))); // NOI18N
        MniCompra.setText("Compras");
        MniCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniCompraActionPerformed(evt);
            }
        });
        Compra.add(MniCompra);

        menuBar.add(Compra);

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.setForeground(new java.awt.Color(0, 0, 0));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/salir.png"))); // NOI18N
        Cerrar.setText("Cerrar");

        MniSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MniSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/exit.png"))); // NOI18N
        MniSalir.setText("Salir del Sistema");
        MniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniSalirActionPerformed(evt);
            }
        });
        Cerrar.add(MniSalir);

        menuBar.add(Cerrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MniCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniCategoriaActionPerformed
        FrmCategorias frm = new FrmCategorias();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniCategoriaActionPerformed

    private void MniVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniVentaActionPerformed
        FrmVenta frm = new FrmVenta(this);
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniVentaActionPerformed

    private void MniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MniSalirActionPerformed

    private void MniArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniArticulosActionPerformed
        FrmProductos frm = new FrmProductos();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniArticulosActionPerformed

    private void MniCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniCompraActionPerformed
        FrmCompras frm = new FrmCompras();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniCompraActionPerformed

    private void MniEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniEmpleadoActionPerformed
        FrmEmpleados frm = new FrmEmpleados();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniEmpleadoActionPerformed

    private void MniMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniMarcasActionPerformed
        FrmMarcas frm = new FrmMarcas();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniMarcasActionPerformed

    private void MniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniClientesActionPerformed
        FrmClientes frm = new FrmClientes();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniClientesActionPerformed

    private void MniProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniProveedoresActionPerformed
        FrmProveedores frm = new FrmProveedores();
        Principal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MniProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cerrar;
    private javax.swing.JMenu Compra;
    private javax.swing.JMenuItem MniArticulos;
    private javax.swing.JMenuItem MniCategoria;
    private javax.swing.JMenuItem MniClientes;
    private javax.swing.JMenuItem MniCompra;
    private javax.swing.JMenuItem MniEmpleado;
    private javax.swing.JMenuItem MniMarcas;
    private javax.swing.JMenuItem MniProveedores;
    private javax.swing.JMenuItem MniSalir;
    private javax.swing.JMenuItem MniVenta;
    private javax.swing.JDesktopPane Principal;
    private Datos.ClienteDAO clienteDAO1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
